INSERT INTO PORTALPAREJAS.PERSONAS (IDPERSONA, NOMBRE, ALTURA, EDAD, GENERO) VALUES (1, 'Juan', 1.85, 32, 'M');

INSERT INTO PORTALPAREJAS.PERSONAS (IDPERSONA, NOMBRE, ALTURA, EDAD, GENERO) VALUES (2, 'Pedro', 1.80, 29, 'M');

INSERT INTO PORTALPAREJAS.PERSONAS (IDPERSONA, NOMBRE, ALTURA, EDAD, GENERO) VALUES (3, 'Fernando', 1.90, 38, 'M');

INSERT INTO PORTALPAREJAS.PERSONAS (IDPERSONA, NOMBRE, ALTURA, EDAD, GENERO) VALUES (4, 'Maria', 1.65, 30, 'F');

INSERT INTO PORTALPAREJAS.PERSONAS (IDPERSONA, NOMBRE, ALTURA, EDAD, GENERO) VALUES (5, 'Ines', 1.75, 25, 'F');

INSERT INTO PORTALPAREJAS.PERSONAS (IDPERSONA, NOMBRE, ALTURA, EDAD, GENERO) VALUES (6, 'Laura', 1.70, 33, 'F');

INSERT INTO PORTALPAREJAS.PERSONAS (IDPERSONA, NOMBRE, ALTURA, EDAD, GENERO) VALUES (7, 'Cristina', 1.76, 33, 'F');

INSERT INTO PORTALPAREJAS.PERSONAS (IDPERSONA, NOMBRE, ALTURA, EDAD, GENERO) VALUES (8, 'Sara', 1.81, 36, 'F');